"""Added new fields to models

Revision ID: 18fafc070648
Revises: f0f7f55d36d4
Create Date: 2024-08-05 00:04:01.722506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18fafc070648'
down_revision = 'f0f7f55d36d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downloads', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('download_path', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('active_until', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('upload_limit', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('upload_limit')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('active_until')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('download_path')
        batch_op.drop_column('verified')
        batch_op.drop_column('downloads')

    # ### end Alembic commands ###
